#!/bin/bash
# The logic to build up your application should be put in this script.
mkdir -p $OPENSHIFT_DATA_DIR/m2/repository
echo -e "<settings><localRepository>$OPENSHIFT_DATA_DIR/m2/repository</localRepository>\n</settings>\n" > $OPENSHIFT_DATA_DIR/settings.xml
cd $OPENSHIFT_REPO_DIR
nohup mvn -Dmaven.test.skip=true -s $OPENSHIFT_DATA_DIR/settings.xml -f $OPENSHIFT_REPO_DIR/pom.xml -Popenshift clean package